export const TODO_OPERATIONS = {
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    REMOVE_TODO: 'REMOVE_TODO'
}

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

export const VISIBILITY_FILTERS = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
    SHOW_COMPLETED: 'SHOW_COMPLETED'
}

export const FETCH_FILTERS = {
    FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
    FETCH_TODOS_FAIL: 'FETCH_TODOS_FAIL',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS' 
}